---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Antidepressants_sp

The goal of this repository is to share the data analysis of the paper *"Population Size, Income and Poor Sanitation Interact to Explain Widespread Streamwater Contamination by Antidepressants in the Metropolitan Region of São Paulo"*.

### Authors

Luis Schiesari<br />
Ricardo Taniwaki<br />
Rodolfo Pelinson *(Conducted data analysis)* <br />
Hagop Barsoumian<br />
Giulia Baldaconi Bispo<br />
Gabriel Lourenço Brejão<br />
Mayumi Hirye<br />
Aline Franco Martins<br />
Jose Luiz Costa<br />


## Data analysis

Influence of volume of sales on the contamination of streamwater by antidepressants<br>
  - [Volume of sales VS antidepressant concentration](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/Sales_contamination.md)<br>

Number, frequency of occurrence and concentration of molecules across the gradient in urban cover<br>
  - [Frequency of molecules across the gradient in urban cover](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/frequency_molecules_loess.md)<br>
  - [Number of molecules across the gradient in urban cover](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/N_molecules_gam.md)<br>
  - [Concentration of molecules across the gradient in urban cover](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/concentration_individual_molecules_gam.md)<br>
  - [Concentration of class of molecules across the gradient in urban cover](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/concentration_molecules_gam.md)<br>

Patterns of co-occurrence among molecules<br>
  - [EMS](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/EMS.md)<br>
  - [RDA](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/RDA.md)<br>

Environmental and socioeconomic predictors of antidepressant concentrations in streamwater<br>
  - [Predictors of total antidepresant concentration in streamwater](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/model_selection_all.md)<br>
\       \   - [Excluding possible misleading observations](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/model_selection_all_exc_obs.md)<br>
\       \   - [Spatial analysis](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/spatial_analyses.md)<br>
\       \   - [Alternative approach: Random Forests](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/randomForest_approach.md)<br>
\       \   - [Distribution of per capita income in the metropolitan region of São Paulo](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/histogram.md)<br>
  - [Predictors of SNRI antidepresant concentration in streamwater](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/model_selection_SNRI.md)<br>
  - [Predictors of SSRI antidepresant concentration in streamwater](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/model_selection_SSRI.md)<br>
  - [Predictors of Aminoketone antidepresant concentration in streamwater](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/model_selection_Aminoketone.md)<br>
  - [Predictors of Tryciclic antidepresant concentration in streamwater](https://github.com/RodolfoPelinson/Antidepressants_sp/blob/master/markdowns/model_selection_Tricyclic.md)<br>

